# Generated by Django 5.0.4 on 2024-05-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('slug', models.CharField(max_length=50, unique=True, verbose_name='URL')),
                ('body', models.TextField(verbose_name='Содержимое')),
                ('preview', models.ImageField(upload_to='blog/%Y/%m', verbose_name='Изображение')),
                ('date_published', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=True, verbose_name='Признак публикации')),
                ('count_views', models.IntegerField(default=0, verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Запись в блоге',
                'verbose_name_plural': 'Записи в блоге',
                'ordering': ['date_published'],
            },
        ),
    ]
